algoritmo "Emprego_3"

var
 salario: real
 contagem: inteiro

inicio

para contagem de 1 ate 10 faca
         escreva (contagem)

         escreva ("- Digite o salário: ")
         leia (salario)
           se (salario <= 2000) entao
             escreval ("Cadidado selecionado para a primeira fase")
           senao
             escreval ("Candidato não preencheu os pré requisitos")
           fimse
fimpara

fimalgoritmo
