algoritmo "organizar_gavetas_comb"
// Função :
// Autor :
// Data : 07/01/2019
// Seção de Declarações 
var
g1,g2,g3:caracter
obj1,obj2,obj3:inteiro

inicio
escreva ("Nomes das Gavetas e tecle ENTER: ") // String dentro do parenteses
leia (g1,g2,g3)

escreva ("Quantidade de Objetos nas Gavetas: ")
leia (obj1,obj2,obj3)

escreval ("Nome da Gaveta ", g1, g2, g3)
escreva ("Quantidade de Objetos: ", obj1, obj2, obj3)

fimalgoritmo
